version: '3.8'

services:
  # PostgreSQL with pgvector
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: EllaZanzi
      POSTGRES_DB: loanapp
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_loan_app_schema_full.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - loan-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d loanapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loanapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - loan-network

volumes:
  postgres_data:

networks:
  loan-network:
    driver: bridge
