global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Loan Backend Application
  - job_name: 'loan-backend'
    static_configs:
      - targets: ['loan-backend-app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL (if you want to monitor database metrics)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # pgAdmin (optional monitoring)
  - job_name: 'pgadmin'
    static_configs:
      - targets: ['pgadmin:80']
    scrape_interval: 30s
